import type { Metadata } from "next";
import Link from "next/link";
import PublicShell from "../components/PublicShell";
import { PublicIcon } from "../components/PublicIcons";

export const metadata: Metadata = { title: "Planes para inmobiliarias", description: "Todos los planes de VAI Prop incluyen la plataforma completa. Elegí la cantidad de usuarios que necesita tu inmobiliaria." };

const plans = [
  { name: "Broker", price: "$25.000", total: "$30.250 final", users: "1 usuario", featured: false },
  { name: "Equipo", price: "$45.000", total: "$54.450 final", users: "Hasta 6 accesos", featured: true },
  { name: "Team Pro", price: "$75.000", total: "$90.750 final", users: "Hasta 11 accesos", featured: false },
];
const included = ["Valuador e informes profesionales", "Factibilidad constructiva preliminar", "Tracker y agenda", "Analytics y gestión de equipo", "VAI Market Data y PER", "Calculadoras e indicadores económicos"];

export default function PlanesPage() { return <PublicShell><section className="px-5 py-20 sm:px-8 lg:px-14"><div className="mx-auto max-w-6xl text-center"><p className="text-sm font-semibold uppercase tracking-[.2em] text-[#E6A930]">Planes simples</p><h1 className="mt-4 text-4xl font-semibold sm:text-6xl">La plataforma completa en todos los planes.</h1><p className="mx-auto mt-6 max-w-3xl text-lg leading-8 text-neutral-300">Solo cambia la cantidad de usuarios habilitados. Elegí la estructura que mejor acompaña a tu inmobiliaria.</p><div className="mt-12 grid gap-6 lg:grid-cols-3">{plans.map((plan) => <article key={plan.name} className={`relative rounded-3xl border p-7 text-left ${plan.featured ? "border-[#E6A930] bg-[#E6A930]/10" : "border-white/10 bg-neutral-950"}`}>{plan.featured && <span className="absolute right-5 top-5 rounded-full bg-[#E6A930] px-3 py-1 text-xs font-bold text-black">Más elegido</span>}<h2 className="text-2xl font-semibold">{plan.name}</h2><p className="mt-5 text-4xl font-semibold">{plan.price}<span className="text-sm font-normal text-neutral-400"> neto/mes</span></p><p className="mt-2 text-sm text-neutral-400">{plan.total}</p><p className="mt-6 rounded-xl border border-white/10 bg-black/30 p-3 text-center font-semibold">{plan.users}</p><ul className="mt-6 space-y-3">{included.map((item) => <li key={item} className="flex gap-3 text-sm text-neutral-300"><PublicIcon name="check" className="h-4 w-4 shrink-0 text-[#E6A930]"/>{item}</li>)}</ul><Link href="/auth/register" className="mt-8 block rounded-full bg-[#E6A930] px-5 py-3 text-center font-bold text-black">Probar gratis 30 días</Link></article>)}</div><div className="mt-8 rounded-3xl border border-white/10 bg-neutral-950 p-8 text-left md:flex md:items-center md:justify-between"><div><h2 className="text-2xl font-semibold">Enterprise</h2><p className="mt-2 max-w-2xl text-neutral-400">Para equipos que necesitan un cupo o acuerdo comercial personalizado. No tiene checkout público.</p></div><a href="https://wa.me/5493513280798" target="_blank" rel="noreferrer" className="mt-5 inline-flex rounded-full border border-[#E6A930] px-6 py-3 font-semibold text-[#f2c76d] md:mt-0">Consultar</a></div></div></section></PublicShell>; }
