import type { Metadata } from "next";
import PublicPage from "../components/PublicPage";

export const metadata: Metadata = { title: "Analizá oportunidades inmobiliarias", description: "Valuación, factibilidad constructiva, VAI Market Data y PER para inmobiliarias que necesitan mejores argumentos comerciales." };

export default function AnalizaPage() {
  return <PublicPage eyebrow="Analizá" title="Tomá decisiones con más información y defendé cada oportunidad con mejores argumentos." intro="Desde una tasación hasta el análisis preliminar de un terreno, VAI Prop organiza la información que tu inmobiliaria necesita para asesorar con claridad, captar mejor y acelerar decisiones." closing="Analizá con criterio. Presentá con confianza." tools={[
      { eyebrow: "Valuación profesional", title: "Valuador VAI", description: "Aplicá el método comparativo, organizá propiedades comparables y generá informes profesionales con la identidad de tu inmobiliaria.", benefits: ["Fundamentá el valor sugerido con comparables.", "Presentá informes claros y consistentes.", "Reducí tareas manuales y mejorá la experiencia del propietario."], image: "/landing/images/vai_propiedad_principal.svg", imageAlt: "Valuador comparativo de propiedades de VAI Prop", reportHref: "/landing/docs/ejemplo_Informe_VAI.pdf", reportLabel: "Ver informe VAI de ejemplo" },
      { eyebrow: "Análisis preliminar", title: "Factibilidad constructiva", description: "Evaluá el potencial comercial preliminar de un terreno para conversar con propietarios, compradores e inversores con una base más ordenada.", benefits: ["Estimá FOS, alturas y superficies.", "Proyectá m² construibles y vendibles.", "Detectá oportunidades antes de avanzar con estudios especializados."], image: "/landing/images/Factibilidad_armado.png", imageAlt: "Herramienta de factibilidad constructiva preliminar", note: "La factibilidad es preliminar y no reemplaza un estudio profesional, anteproyecto, consulta normativa ni aprobación municipal.", reportHref: "/landing/docs/ejemplo_Informe_Factibilidad.pdf", reportLabel: "Ver informe de factibilidad" },
      { eyebrow: "Datos de mercado", title: "VAI Market Data", description: "Consultá estadísticas agregadas y anónimas para contextualizar precios, tiempos de venta y comportamiento del mercado.", benefits: ["Compará promedios, medianas y rangos observados.", "Analizá valor por m² y tiempo promedio de venta.", "Identificá zonas y tipologías con mayor actividad."], image: "/landing/images/tools/vai-market-data.svg", imageAlt: "Panel VAI Market Data con estadísticas inmobiliarias", accelerator: true },
      { eyebrow: "Análisis de inversión", title: "PER inmobiliario", description: "Relacioná precio y renta para convertir un análisis económico en una referencia fácil de explicar a compradores e inversores.", benefits: ["Compará oportunidades con un criterio homogéneo.", "Detectá propiedades competitivas o exigidas.", "Sumá un argumento concreto a la conversación comercial."], image: "/landing/images/tools/per-inmobiliario.svg", imageAlt: "Calculadora de PER inmobiliario", accelerator: true, note: "El PER es una referencia orientativa y debe interpretarse junto con ubicación, estado, demanda, gastos y demás variables de cada operación." },
    ]} />;
}
