"use client";

import dynamic from "next/dynamic";
import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "#lib/supabaseClient";
import { useAuth } from "@/context/AuthContext";
import { useTheme } from "@/context/ThemeContext";
import type { BrandData, CanvasElement, PlateTemplateId, PropertyData, PropertyStatus } from "./types";
import { DESIGN_HEIGHT, DESIGN_WIDTH, getTemplate, PLATE_TEMPLATES } from "./templates";
import type { KonvaCanvasHandle } from "./KonvaCanvas";

const KonvaCanvas = dynamic(() => import("./KonvaCanvas"), { ssr: false });
const MAX_FILE_MB = 12;
const STATUS_OPTIONS: PropertyStatus[] = ["", "RESERVADO", "VENDIDO", "ALQUILADO", "EN ALQUILER", "OPORTUNIDAD", "NUEVO PRECIO"];
const DEFAULT_DATA: PropertyData = { operation:"VENTA",title:"CASA EN VENTA",currency:"USD",price:"120.000",oldPrice:"135.000",location:"Córdoba Capital",ambients:"5",bedrooms:"3",bathrooms:"2",garages:"1",coveredArea:"160",totalArea:"300",highlight:"Diseño, ubicación y oportunidad",status:"",showStatus:false,showPrice:true,showLocation:true,showFeatures:true,showFooter:true,showLogo:true,primaryColor:"#111827",secondaryColor:"#d5ad55",accentColor:"#ffffff",backgroundColor:"#f7f4ee" };

function fileToDataUrl(file:File):Promise<string>{return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=()=>reject(r.error);r.readAsDataURL(file);});}
function normalizeProfessionalName(raw?:string|null){return raw?raw.replace(/cpi\s*\d+/gi,"").replace(/[·|-]+$/g,"").trim():"";}
function formatLicense(raw?:string|null){const clean=String(raw||"").trim();return clean?( /^cpi\b/i.test(clean)?clean:`CPI ${clean}`):"";}
function safeName(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9-_]+/g,"-").replace(/^-+|-+$/g,"").toLowerCase().slice(0,70)||"placa-inmobiliaria";}
function cloneElements(id:PlateTemplateId){return getTemplate(id).elements.map(e=>({...e}));}

export default function PlateEditor({mode}:{mode:"empresa"|"asesor"}){
  const {user}=useAuth(); const {primaryColor:themeColor,logoUrl:themeLogo}=useTheme();
  const canvasRef=useRef<KonvaCanvasHandle|null>(null); const previewRef=useRef<HTMLDivElement|null>(null);
  const [templateId,setTemplateId]=useState<PlateTemplateId>("template-1"); const [elements,setElements]=useState<CanvasElement[]>(()=>cloneElements("template-1"));
  const [data,setData]=useState<PropertyData>(DEFAULT_DATA); const [images,setImages]=useState<Array<string|null>>(Array(5).fill(null));
  const [brand,setBrand]=useState<BrandData>({companyName:"VAI Prop",professionalName:"Profesional inmobiliario",license:"",phone:"",logoUrl:null,primaryColor:themeColor||DEFAULT_DATA.primaryColor});
  const [selectedId,setSelectedId]=useState<string|null>(null); const [history,setHistory]=useState<CanvasElement[][]>([]); const [future,setFuture]=useState<CanvasElement[][]>([]);
  const [message,setMessage]=useState<string|null>(null); const [exporting,setExporting]=useState(false); const [previewWidth,setPreviewWidth]=useState(640);
  const selected=elements.find(e=>e.id===selectedId)||null; const activeTemplate=getTemplate(templateId);
  const brandText=[brand.companyName,brand.professionalName,brand.license].filter(Boolean).join(" · "); const contactText=brand.phone||"";
  const scale=Math.min(1,previewWidth/DESIGN_WIDTH);

  useEffect(()=>{const el=previewRef.current;if(!el)return;const obs=new ResizeObserver(([entry])=>setPreviewWidth(Math.max(280,entry.contentRect.width-24)));obs.observe(el);return()=>obs.disconnect();},[]);
  useEffect(()=>{let active=true;const load=async()=>{if(!user?.id)return;try{const profile=user as any;let company:any=null;if(mode==="asesor"&&profile.empresa_id){const r=await supabase.from("empresas").select("id,nombre_comercial,matriculado,cpi,telefono,logo_url,color").eq("id",profile.empresa_id).maybeSingle();if(r.error)throw r.error;company=r.data;}else{const r=await supabase.from("empresas").select("id,nombre_comercial,matriculado,cpi,telefono,logo_url,color").or(`user_id.eq.${user.id},id_usuario.eq.${user.id}`).limit(1).maybeSingle();if(r.error)throw r.error;company=r.data;}if(!active)return;const name=`${profile?.nombre||""} ${profile?.apellido||""}`.trim();const next={companyName:company?.nombre_comercial||profile?.inmobiliaria||"VAI Prop",professionalName:name||normalizeProfessionalName(company?.matriculado||profile?.matriculado_nombre)||"Profesional inmobiliario",license:formatLicense(company?.cpi||profile?.cpi),phone:mode==="asesor"?(profile?.telefono||company?.telefono||""):(company?.telefono||profile?.telefono||""),logoUrl:company?.logo_url||themeLogo||null,primaryColor:company?.color||themeColor||DEFAULT_DATA.primaryColor};setBrand(next);setData(p=>({...p,primaryColor:next.primaryColor}));}catch(e){console.error(e);setMessage("No se pudo cargar toda la identidad corporativa. Podés continuar igualmente.");}};void load();return()=>{active=false};},[mode,themeColor,themeLogo,user]);

  const commit=(next:CanvasElement[])=>{setHistory(h=>[...h.slice(-39),elements.map(e=>({...e}))]);setFuture([]);setElements(next);};
  const changeElement=(id:string,patch:Partial<CanvasElement>)=>setElements(current=>current.map(e=>e.id===id?{...e,...patch}:e));
  const changeElementCommitted=(id:string,patch:Partial<CanvasElement>)=>commit(elements.map(e=>e.id===id?{...e,...patch}:e));
  const undo=()=>{const prev=history.at(-1);if(!prev)return;setFuture(f=>[elements.map(e=>({...e})),...f]);setElements(prev);setHistory(h=>h.slice(0,-1));setSelectedId(null);};
  const redo=()=>{const next=future[0];if(!next)return;setHistory(h=>[...h,elements.map(e=>({...e}))]);setElements(next);setFuture(f=>f.slice(1));setSelectedId(null);};
  const chooseTemplate=(id:PlateTemplateId)=>{setTemplateId(id);setElements(cloneElements(id));setHistory([]);setFuture([]);setSelectedId(null);};
  const applyColors=()=>setElements(current=>current.map(e=>{if(e.colorRole==="primary")return{...e,fill:data.primaryColor};if(e.colorRole==="secondary")return{...e,fill:data.secondaryColor};if(e.colorRole==="accent")return{...e,fill:data.accentColor};if(e.colorRole==="background")return{...e,fill:data.backgroundColor};return e;}));
  useEffect(()=>{applyColors();},[data.primaryColor,data.secondaryColor,data.accentColor,data.backgroundColor]);

  const upload=async(slot:number,file:File|null)=>{if(!file)return;if(!file.type.startsWith("image/")||file.size>MAX_FILE_MB*1024*1024){setMessage(`Usá JPG, PNG o WEBP de hasta ${MAX_FILE_MB} MB.`);return;}try{const url=await fileToDataUrl(file);setImages(prev=>prev.map((v,i)=>i===slot?url:v));setMessage(null);}catch{setMessage("No se pudo leer la imagen.");}};
  const exportPlate=(mime:"image/png"|"image/jpeg")=>{setExporting(true);try{const url=canvasRef.current?.exportImage(mime);if(!url)throw new Error();const a=document.createElement("a");a.href=url;a.download=`${safeName(data.title)}-${templateId}.${mime==="image/png"?"png":"jpg"}`;a.click();}catch{setMessage("No se pudo exportar la placa.");}finally{setExporting(false);}};
  const duplicate=()=>{if(!selected)return;const copy={...selected,id:`${selected.id}-copy-${Date.now()}`,name:`${selected.name} copia`,x:selected.x+25,y:selected.y+25,zIndex:Math.max(...elements.map(e=>e.zIndex))+1};commit([...elements,copy]);setSelectedId(copy.id);};
  const remove=()=>{if(!selected||selected.locked)return;commit(elements.filter(e=>e.id!==selected.id));setSelectedId(null);};
  const moveLayer=(dir:1|-1)=>{if(!selected)return;const next=[...elements];const sorted=[...next].sort((a,b)=>a.zIndex-b.zIndex);const idx=sorted.findIndex(e=>e.id===selected.id);const swap=idx+dir;if(swap<0||swap>=sorted.length)return;const a=sorted[idx],b=sorted[swap],za=a.zIndex;changeElementCommitted(a.id,{zIndex:b.zIndex});setElements(current=>current.map(e=>e.id===b.id?{...e,zIndex:za}:e));};
  const addText=()=>{const z=Math.max(...elements.map(e=>e.zIndex))+1;const el:CanvasElement={id:`text-${Date.now()}`,kind:"text",name:"Texto libre",x:120,y:200,width:520,height:100,text:"NUEVO TEXTO",fontSize:48,fontFamily:"Arial",fontStyle:"bold",fill:"#ffffff",align:"left",zIndex:z,visible:true,draggable:true};commit([...elements,el]);setSelectedId(el.id);};
  const addShape=(kind:"rect"|"circle")=>{const z=Math.max(...elements.map(e=>e.zIndex))+1;const el:CanvasElement={id:`${kind}-${Date.now()}`,kind,name:kind==="rect"?"Rectángulo":"Círculo",x:180,y:250,width:220,height:160,fill:data.secondaryColor,cornerRadius:kind==="rect"?24:0,zIndex:z,visible:true,draggable:true};commit([...elements,el]);setSelectedId(el.id);};

  return <main className="pe-page">
    <header className="pe-header"><div><p className="eyebrow">VAI TOOLS</p><h1>Creador de placas</h1><p>Editor local estilo Canva. Nada de lo generado se guarda en la base de datos.</p></div><div className="top-actions"><button onClick={undo} disabled={!history.length}>Deshacer</button><button onClick={redo} disabled={!future.length}>Rehacer</button><button onClick={()=>exportPlate("image/png")} disabled={exporting} className="primary">Descargar PNG</button></div></header>
    {message&&<div className="message">{message}<button onClick={()=>setMessage(null)}>×</button></div>}
    <section className="editor-layout">
      <aside className="sidebar left"><h2>Plantillas</h2><div className="template-grid">{PLATE_TEMPLATES.map(t=><button key={t.id} onClick={()=>chooseTemplate(t.id)} className={templateId===t.id?"template active":"template"}><span className="thumb" style={{background:t.previewGradient}}><b>{t.imageCount}</b></span><strong>{t.name}</strong><small>{t.description}</small></button>)}</div>
        <h2>Fotos ({activeTemplate.imageCount})</h2>{Array.from({length:activeTemplate.imageCount}).map((_,i)=><label className="upload" key={i}><span>{images[i]?`Foto ${i+1} cargada`:`Cargar foto ${i+1}`}</span><input type="file" accept="image/*" onChange={e=>void upload(i,e.target.files?.[0]||null)}/></label>)}
      </aside>
      <div className="canvas-area"><div className="toolbar"><button onClick={addText}>+ Texto</button><button onClick={()=>addShape("rect")}>+ Rectángulo</button><button onClick={()=>addShape("circle")}>+ Círculo</button><button onClick={duplicate} disabled={!selected}>Duplicar</button><button onClick={remove} disabled={!selected||selected.locked}>Eliminar elemento</button></div><div className="preview" ref={previewRef}><KonvaCanvas ref={canvasRef} elements={elements} data={data} images={images} logoUrl={brand.logoUrl} brandText={brandText} contactText={contactText} selectedId={selectedId} onSelect={setSelectedId} onChange={changeElement} scale={scale}/></div><div className="mobile-export"><button onClick={()=>exportPlate("image/png")} className="primary">Descargar PNG</button><button onClick={()=>exportPlate("image/jpeg")}>Descargar JPG</button></div></div>
      <aside className="sidebar right"><h2>Contenido</h2><div className="field-grid"><label>Operación<input value={data.operation} onChange={e=>setData({...data,operation:e.target.value})}/></label><label>Título<input value={data.title} onChange={e=>setData({...data,title:e.target.value})}/></label><label>Ubicación<input value={data.location} onChange={e=>setData({...data,location:e.target.value})}/></label><label>Descripción<textarea value={data.highlight} onChange={e=>setData({...data,highlight:e.target.value})}/></label><div className="two"><label>Moneda<input value={data.currency} onChange={e=>setData({...data,currency:e.target.value})}/></label><label>Precio<input value={data.price} onChange={e=>setData({...data,price:e.target.value})}/></label></div><div className="two"><label>Ambientes<input value={data.ambients} onChange={e=>setData({...data,ambients:e.target.value})}/></label><label>Dormitorios<input value={data.bedrooms} onChange={e=>setData({...data,bedrooms:e.target.value})}/></label></div><div className="two"><label>Baños<input value={data.bathrooms} onChange={e=>setData({...data,bathrooms:e.target.value})}/></label><label>Cochera<input value={data.garages} onChange={e=>setData({...data,garages:e.target.value})}/></label></div><div className="two"><label>M² cubiertos<input value={data.coveredArea} onChange={e=>setData({...data,coveredArea:e.target.value})}/></label><label>M² totales<input value={data.totalArea} onChange={e=>setData({...data,totalArea:e.target.value})}/></label></div><label>Estado<select value={data.status} onChange={e=>setData({...data,status:e.target.value as PropertyStatus,showStatus:Boolean(e.target.value)})}>{STATUS_OPTIONS.map(s=><option key={s||"none"} value={s}>{s||"Sin sello"}</option>)}</select></label></div>
        <h2>Colores</h2><div className="colors">{([['primaryColor','Principal'],['secondaryColor','Secundario'],['accentColor','Acento'],['backgroundColor','Fondo']] as const).map(([key,label])=><label key={key}>{label}<input type="color" value={data[key]} onChange={e=>setData({...data,[key]:e.target.value})}/></label>)}</div>
        <h2>Elemento seleccionado</h2>{selected?<div className="inspector"><strong>{selected.name}</strong>{selected.kind==="text"&&!selected.textRole&&<label>Texto<input value={selected.text||""} onChange={e=>changeElement(selected.id,{text:e.target.value})}/></label>}{selected.kind==="text"&&<><label>Tamaño<input type="number" value={selected.fontSize||32} onChange={e=>changeElement(selected.id,{fontSize:Number(e.target.value)})}/></label><label>Color<input type="color" value={selected.fill||"#111827"} onChange={e=>changeElement(selected.id,{fill:e.target.value})}/></label></>}{selected.kind!=="image"&&selected.kind!=="text"&&<label>Color<input type="color" value={selected.fill||"#111827"} onChange={e=>changeElement(selected.id,{fill:e.target.value})}/></label>}<div className="two"><label>X<input type="number" value={Math.round(selected.x)} onChange={e=>changeElement(selected.id,{x:Number(e.target.value)})}/></label><label>Y<input type="number" value={Math.round(selected.y)} onChange={e=>changeElement(selected.id,{y:Number(e.target.value)})}/></label></div><div className="two"><button onClick={()=>moveLayer(1)}>Traer adelante</button><button onClick={()=>moveLayer(-1)}>Enviar atrás</button></div><label className="check"><input type="checkbox" checked={Boolean(selected.locked)} onChange={e=>changeElement(selected.id,{locked:e.target.checked})}/> Bloquear elemento</label></div>:<p className="muted">Seleccioná un objeto del lienzo para moverlo, redimensionarlo, rotarlo o editarlo.</p>}
        <h2>Descarga</h2><button className="primary full" onClick={()=>exportPlate("image/png")} disabled={exporting}>Descargar PNG</button><button className="full" onClick={()=>exportPlate("image/jpeg")} disabled={exporting}>Descargar JPG</button>
      </aside>
    </section>
    <style jsx>{`
      .pe-page{padding:20px;background:#f5f7fb;min-height:100vh;color:#0f172a}.pe-header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:18px}.pe-header h1{font-size:30px;margin:2px 0 6px}.pe-header p{margin:0;color:#64748b}.eyebrow{font-size:11px!important;font-weight:900;letter-spacing:.16em;color:#b1842e!important}.top-actions,.toolbar,.mobile-export{display:flex;gap:8px;flex-wrap:wrap}button{border:1px solid #d7dde6;background:#fff;border-radius:10px;padding:9px 12px;font-weight:700;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}button.primary{background:#0f172a;color:#fff;border-color:#0f172a}.message{display:flex;justify-content:space-between;padding:12px 14px;background:#fff7ed;border:1px solid #fed7aa;border-radius:12px;margin-bottom:12px}.editor-layout{display:grid;grid-template-columns:280px minmax(420px,1fr) 300px;gap:14px;align-items:start}.sidebar{background:#fff;border:1px solid #e2e8f0;border-radius:16px;padding:14px;max-height:calc(100vh - 135px);overflow:auto;position:sticky;top:86px}.sidebar h2{font-size:13px;text-transform:uppercase;letter-spacing:.08em;margin:10px 0}.template-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.template{display:flex;flex-direction:column;text-align:left;padding:7px}.template.active{border-color:#b1842e;box-shadow:0 0 0 2px rgba(177,132,46,.15)}.thumb{height:80px;border-radius:8px;display:grid;place-items:center;color:#fff;margin-bottom:5px}.thumb b{font-size:20px;background:rgba(0,0,0,.35);border-radius:50%;width:34px;height:34px;display:grid;place-items:center}.template strong{font-size:12px}.template small{font-size:10px;color:#64748b;line-height:1.2}.upload{display:block;border:1px dashed #cbd5e1;border-radius:10px;padding:10px;margin:7px 0;font-size:12px;font-weight:700}.upload input{display:block;width:100%;margin-top:5px;font-size:10px}.canvas-area{min-width:0}.toolbar{margin-bottom:8px}.preview{background:#dfe5ec;border:1px solid #cbd5e1;border-radius:16px;padding:12px;display:flex;justify-content:center;overflow:auto;min-height:500px}.mobile-export{justify-content:center;margin-top:10px}.field-grid label,.inspector label{display:block;font-size:11px;font-weight:800;color:#475569;margin:7px 0}.field-grid input,.field-grid textarea,.field-grid select,.inspector input{width:100%;box-sizing:border-box;border:1px solid #d7dde6;border-radius:8px;padding:8px;margin-top:4px;font:inherit}.field-grid textarea{min-height:62px;resize:vertical}.two{display:grid;grid-template-columns:1fr 1fr;gap:8px}.colors{display:grid;grid-template-columns:1fr 1fr;gap:7px}.colors label{font-size:10px;font-weight:800}.colors input{display:block;width:100%;height:36px;border:0;padding:0}.inspector{border:1px solid #e2e8f0;border-radius:12px;padding:10px}.check{display:flex!important;gap:7px;align-items:center}.check input{width:auto!important;margin:0!important}.full{width:100%;margin:4px 0}.muted{font-size:12px;color:#64748b}.mobile-export{display:none}
      @media(max-width:1180px){.editor-layout{grid-template-columns:240px minmax(380px,1fr)}.sidebar.right{position:static;grid-column:1/-1;max-height:none;display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.sidebar.right h2{grid-column:auto}.field-grid{grid-column:span 2}}
      @media(max-width:800px){.pe-page{padding:12px}.pe-header{display:block}.top-actions{margin-top:10px}.editor-layout{display:flex;flex-direction:column}.sidebar{position:static;max-height:none;width:100%;box-sizing:border-box}.canvas-area{width:100%}.template-grid{grid-template-columns:repeat(2,1fr)}.sidebar.right{display:block}.preview{min-height:360px;padding:6px}.mobile-export{display:flex;position:sticky;bottom:8px;background:rgba(255,255,255,.95);padding:8px;border-radius:12px;z-index:20}.top-actions .primary{display:none}}
    `}</style>
  </main>;
}
