export const runtime="nodejs";export const dynamic="force-dynamic";
import {NextResponse} from "next/server";import{createClient}from"@supabase/supabase-js";import{supabaseServer}from"#lib/supabaseServer";
const admin=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.SUPABASE_SERVICE_ROLE_KEY!);
async function ok(){const s=supabaseServer();const{data:{user}}=await s.auth.getUser();if(!user)return false;const{data:p}=await admin.from("profiles").select("role").or(`id.eq.${user.id},user_id.eq.${user.id}`).limit(1).maybeSingle();return p?.role==="super_admin"||p?.role==="super_admin_root";}
const approved=(v:any)=>["paid","approved","accredited","aprobado","acreditado","completado"].includes(String(v??"").toLowerCase());const n=(v:any)=>Number.isFinite(Number(v))?Number(v):0;
export async function GET(req:Request){try{if(!(await ok()))return NextResponse.json({error:"Acceso denegado."},{status:403});const u=new URL(req.url);const desde=u.searchParams.get("desde")||new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10);const hasta=u.searchParams.get("hasta")||new Date().toISOString().slice(0,10);const empresaId=u.searchParams.get("empresaId");
let mq=admin.from("movimientos_financieros").select("id,empresa_id,fecha,monto_neto,total,estado,origen,referencia_pasarela,metadata").gte("fecha",`${desde}T00:00:00Z`).lte("fecha",`${hasta}T23:59:59Z`);if(empresaId)mq=mq.eq("empresa_id",empresaId);let sq=admin.from("suscripciones").select("id,empresa_id,estado,inicio,fin,ciclo_inicio,ciclo_fin,metadata,created_at,updated_at");if(empresaId)sq=sq.eq("empresa_id",empresaId);const[mr,sr]=await Promise.all([mq,sq]);if(mr.error)throw new Error(mr.error.message);if(sr.error)throw new Error(sr.error.message);
const seen=new Set<string>();let neto=0,total=0,movs=0;const empresas=new Set<string>();for(const m of mr.data??[]){if(!approved(m.estado)||String(m.origen??"").toLowerCase().includes("simul"))continue;const key=String(m.referencia_pasarela??m.metadata?.externo_payment_id??m.id);if(seen.has(key))continue;seen.add(key);neto+=n(m.monto_neto??m.total);total+=n(m.total??m.monto_neto);movs++;empresas.add(String(m.empresa_id));}
for(const s of sr.data??[]){const meta:any=s.metadata??{};if(!approved(meta.payment_status))continue;const d=new Date(s.updated_at??s.created_at??s.inicio);if(Number.isNaN(d.getTime())||d<new Date(`${desde}T00:00:00Z`)||d>new Date(`${hasta}T23:59:59Z`))continue;const key=String(meta.externo_payment_id??`sub:${s.id}`);if(seen.has(key))continue;seen.add(key);neto+=n(meta.precio_neto_final??meta.precio_total_final);total+=n(meta.precio_total_final??meta.precio_neto_final);movs++;empresas.add(String(s.empresa_id));}
const now=Date.now();let mrr=0;for(const s of sr.data??[]){if(String(s.estado).toLowerCase()!=="activa")continue;const ini=new Date(s.ciclo_inicio??s.inicio).getTime(),fin=new Date(s.ciclo_fin??s.fin).getTime();if(!Number.isFinite(ini)||!Number.isFinite(fin)||ini>now||fin<=now)continue;mrr+=n((s.metadata as any)?.precio_neto_final??(s.metadata as any)?.precio_total_final);}
return NextResponse.json({rango:{desde,hasta},mrr_neto:mrr,ingresos_neto_total:neto,ingresos_con_iva:total,arpu_neto:empresas.size?neto/empresas.size:0,empresas_activas:empresas.size,churn_empresas:0,upgrades:0,downgrades:0,movimientos_acreditados:movs});}catch(e:any){return NextResponse.json({error:e?.message??"Error inesperado."},{status:500});}}
