import type { Metadata } from "next";
import PublicPage from "../components/PublicPage";

export const metadata: Metadata = { title: "Medí el rendimiento de tu inmobiliaria", description: "Analytics, indicadores económicos y calculadoras para medir rendimiento, alquileres y créditos UVA en una inmobiliaria." };

export default function MediPage() {
  return <PublicPage eyebrow="Medí" title="Convertí la actividad diaria en indicadores útiles para decidir y mejorar." intro="Medí producción, conversión, captaciones, cierres y honorarios. Complementá el análisis con calculadoras e indicadores económicos disponibles dentro de la plataforma." closing="Lo que se mide se puede acompañar, mejorar y escalar." tools={[
      { eyebrow: "Rendimiento", title: "Analytics inmobiliario", description: "Observá la evolución comercial de la empresa y de cada asesor con indicadores diseñados para entender el trabajo real del equipo.", benefits: ["Medí prospectos, captaciones, cierres y conversión.", "Analizá honorarios y montos de operaciones.", "Compará períodos, zonas, tipologías y asesores."], image: "/landing/images/tools/analytics-inmobiliario.svg", imageAlt: "Dashboard de analytics inmobiliario" },
      { eyebrow: "Gestión locativa", title: "Calculadora de alquileres", description: "Simulá ajustes y escenarios para acompañar conversaciones con propietarios e inquilinos con referencias claras.", benefits: ["Calculá actualizaciones de alquiler.", "Compará escenarios y períodos.", "Apoyá el seguimiento de contratos y administraciones."], image: "/landing/images/tools/calculadora-alquileres.svg", imageAlt: "Calculadora de actualización de alquileres" },
      { eyebrow: "Financiación", title: "Calculadora de créditos UVA", description: "Estimá escenarios orientativos de financiación para acompañar a compradores y asesores durante la evaluación de una operación.", benefits: ["Simulá monto, tasa y plazo.", "Obtené una cuota inicial aproximada.", "Facilitá conversaciones comerciales con una referencia rápida."], image: "/landing/images/tools/calculadora-creditos-uva.svg", imageAlt: "Calculadora de créditos UVA", note: "Los resultados son orientativos y no reemplazan la información oficial de una entidad financiera. Las cuotas pueden variar por UVA, seguros, gastos y condiciones particulares." },
      { eyebrow: "Contexto económico", title: "Indicadores y cotización del dólar", description: "Consultá referencias económicas dentro de la plataforma para contextualizar precios, alquileres y decisiones comerciales.", benefits: ["Accedé a cotizaciones de referencia.", "Revisá indicadores relevantes para el mercado inmobiliario.", "Centralizá información útil sin salir del flujo de trabajo."], image: "/landing/images/tools/indicadores-economicos.svg", imageAlt: "Indicadores económicos y cotización del dólar", note: "Las cotizaciones e indicadores son informativos y pueden presentar diferencias o demoras respecto de sus fuentes oficiales." },
    ]} />;
}
