"use client";
import { useEffect, useMemo, useState } from "react";

type Data={kpis:{empresasTotal:number;empresasConAcceso:number;clientesPagos:number;trials:number;desarrollo:number;suspendidas:number;sinCiclo:number;vencen7d:number;acuerdosPorVencer:number;ingresosPeriodo:number};ingresosMensuales:Array<{mes:string;monto:number}>;distribucion:Array<{label:string;value:number}>};
const money=(n:number)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(n||0); const num=(n:number)=>new Intl.NumberFormat("es-AR").format(n||0);
export default function AdminDashboardClient(){const[months,setMonths]=useState(6);const[data,setData]=useState<Data|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
useEffect(()=>{let alive=true;setLoading(true);setError(null);fetch(`/api/admin/dashboard?months=${months}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error(await r.text());return r.json();}).then(x=>{if(alive)setData(x);}).catch(e=>{if(alive)setError(e?.message??"No se pudo cargar.");}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false};},[months]);
const max=useMemo(()=>Math.max(1,...(data?.ingresosMensuales??[]).map(x=>x.monto)),[data]);const totalDist=useMemo(()=>Math.max(1,...(data?.distribucion??[]).map(x=>x.value)),[data]);const k=data?.kpis;
return <main className="mx-auto w-full max-w-[1600px] space-y-6 p-4 md:p-6 xl:p-8"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-amber-600">VAI Prop · Administración</p><h1 className="mt-1 text-2xl font-bold md:text-3xl">Centro de control</h1><p className="mt-2 text-sm text-slate-500">Acceso, renovaciones, acuerdos e ingresos acreditados.</p></div><nav className="grid grid-cols-2 gap-2 sm:flex"><a href="/dashboard/admin/empresas" className="rounded-xl bg-slate-950 px-4 py-2.5 text-center text-sm font-semibold text-white">Gestionar empresas</a><a href="/dashboard/admin/cashflow" className="rounded-xl border px-4 py-2.5 text-center text-sm font-semibold">Ver cashflow</a></nav></header>{error?<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>:null}
<section className="grid grid-cols-2 gap-3 lg:grid-cols-4 2xl:grid-cols-6">{[["Clientes pagos",k?.clientesPagos??0,"Ciclo vigente"],["Con acceso",k?.empresasConAcceso??0,`${k?.empresasTotal??0} empresas`],["Ingresos acreditados",money(k?.ingresosPeriodo??0),`${months===1?"Mes actual":`Últimos ${months} meses`}`],["Acuerdos por vencer",k?.acuerdosPorVencer??0,"Próximos 30 días"],["Ciclos por vencer",k?.vencen7d??0,"Próximos 7 días"],["Suspendidas",k?.suspendidas??0,`${k?.sinCiclo??0} sin ciclo`]].map(([l,v,h])=><article key={String(l)} className="min-w-0 rounded-2xl border bg-white p-4 shadow-sm dark:bg-neutral-900"><p className="truncate text-xs text-slate-500">{l}</p><p className="mt-2 break-words text-2xl font-bold">{typeof v==="number"?num(v):v}</p><p className="mt-1 text-xs text-slate-400">{h}</p></article>)}</section>
<section className="grid gap-4 xl:grid-cols-[1.6fr_1fr]"><article className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-neutral-900 md:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">Ingresos acreditados</h2><p className="text-xs text-slate-500">Pagos reales, sin simulaciones y sin duplicados.</p></div><select value={months} onChange={e=>setMonths(Number(e.target.value))} className="w-full rounded-xl border bg-transparent px-3 py-2 text-sm sm:w-auto"><option value={1}>Mes actual</option><option value={3}>Últimos 3 meses</option><option value={6}>Últimos 6 meses</option><option value={12}>Último año</option></select></div><div className="mt-6 flex h-56 items-end gap-2 overflow-x-auto pb-2 sm:gap-4">{loading?<p className="text-sm text-slate-500">Cargando…</p>:(data?.ingresosMensuales??[]).map(x=><div key={x.mes} className="flex h-full min-w-[58px] flex-1 flex-col justify-end gap-2 text-center"><span className="text-[10px] font-medium text-slate-500">{money(x.monto)}</span><div className="mx-auto w-full max-w-20 rounded-t-xl bg-slate-900 dark:bg-amber-500" style={{height:`${Math.max(4,(x.monto/max)*100)}%`}}/><span className="text-xs text-slate-500">{x.mes.slice(5)}/{x.mes.slice(2,4)}</span></div>)}</div></article><article className="rounded-2xl border bg-white p-4 shadow-sm dark:bg-neutral-900 md:p-5"><h2 className="font-semibold">Estado de cartera</h2><div className="mt-6 space-y-5">{(data?.distribucion??[]).map(x=><div key={x.label}><div className="mb-2 flex justify-between text-sm"><span>{x.label}</span><strong>{num(x.value)}</strong></div><div className="h-3 overflow-hidden rounded-full bg-slate-100 dark:bg-neutral-800"><div className="h-full rounded-full bg-amber-500" style={{width:`${(x.value/totalDist)*100}%`}}/></div></div>)}</div><div className="mt-6 grid grid-cols-2 gap-3 border-t pt-4 text-center"><div><p className="text-xl font-bold">{num(k?.trials??0)}</p><p className="text-xs text-slate-500">Trials</p></div><div><p className="text-xl font-bold">{num(k?.desarrollo??0)}</p><p className="text-xs text-slate-500">Desarrollo</p></div></div></article></section></main>}
