"use client";

import { useEffect, useMemo, useState } from "react";
import { getCashflowKpis, type CashflowKpisResponse } from "#lib/adminCashflowApi";

type EmpresaResumen={empresa_id:string;empresa_nombre:string;cuit:string|null;plan_nombre:string|null;plan_activo:boolean;estado_acceso?:"activa"|"suspendida"|"sin_ciclo";fecha_inicio:string|null;fecha_fin:string|null;ingresos_neto_periodo:number;ingresos_con_iva_periodo:number;mrr_neto_actual:number;movimientos_count:number;ultimo_movimiento:string|null;};
type EmpresasPaged={page:number;pageSize:number;total:number;items:EmpresaResumen[]};
const pad=(n:number)=>String(n).padStart(2,"0");function monthRange(){const d=new Date(),f=new Date(d.getFullYear(),d.getMonth(),1),l=new Date(d.getFullYear(),d.getMonth()+1,0);return{desde:`${f.getFullYear()}-${pad(f.getMonth()+1)}-${pad(f.getDate())}`,hasta:`${l.getFullYear()}-${pad(l.getMonth()+1)}-${pad(l.getDate())}`};}
const money=(n?:number|null)=>new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0}).format(Number(n??0));const date=(v?:string|null)=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("es-AR",{dateStyle:"medium"}).format(d)};
export default function CashflowClient(){const def=monthRange();const[desde,setDesde]=useState(def.desde),[hasta,setHasta]=useState(def.hasta),[q,setQ]=useState(""),[estado,setEstado]=useState("todos"),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(20),[kpis,setKpis]=useState<CashflowKpisResponse|null>(null),[empresas,setEmpresas]=useState<EmpresasPaged|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState<string|null>(null);const can=useMemo(()=>!!desde&&!!hasta,[desde,hasta]);
async function load(){if(!can)return;setLoading(true);setError(null);try{const params=new URLSearchParams({desde,hasta,page:String(page),pageSize:String(pageSize),estado_plan:estado});if(q.trim())params.set("q",q.trim());const[k,r]=await Promise.all([getCashflowKpis({desde,hasta}),fetch(`/api/admin/cashflow/empresas?${params}`,{cache:"no-store"})]);if(!r.ok)throw new Error(await r.text());setKpis(k);setEmpresas(await r.json());}catch(e:any){setError(e?.message??"No se pudo cargar cashflow.");}finally{setLoading(false)}}
useEffect(()=>{load();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[desde,hasta,estado,page,pageSize]);const pages=Math.max(1,Math.ceil((empresas?.total??0)/pageSize));
return <section className="space-y-5"><div className="rounded-2xl border bg-white p-4 dark:bg-neutral-900"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-5"><label><span className="mb-1 block text-xs text-slate-500">Desde</span><input type="date" value={desde} onChange={e=>{setPage(1);setDesde(e.target.value)}} className="w-full rounded-xl border bg-transparent px-3 py-2.5"/></label><label><span className="mb-1 block text-xs text-slate-500">Hasta</span><input type="date" value={hasta} onChange={e=>{setPage(1);setHasta(e.target.value)}} className="w-full rounded-xl border bg-transparent px-3 py-2.5"/></label><label className="sm:col-span-2"><span className="mb-1 block text-xs text-slate-500">Buscar empresa</span><input value={q} onChange={e=>{setPage(1);setQ(e.target.value)}} onKeyDown={e=>{if(e.key==="Enter")load()}} placeholder="Nombre o CUIT" className="w-full rounded-xl border bg-transparent px-3 py-2.5"/></label><label><span className="mb-1 block text-xs text-slate-500">Estado</span><select value={estado} onChange={e=>{setPage(1);setEstado(e.target.value)}} className="w-full rounded-xl border bg-transparent px-3 py-2.5"><option value="todos">Todos</option><option value="activo">Activa</option><option value="inactivo">Suspendida / sin ciclo</option></select></label></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={load} disabled={loading} className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Aplicar filtros</button>{loading?<span className="self-center text-xs text-slate-500">Cargando…</span>:null}{error?<span className="self-center text-xs text-red-600">{error}</span>:null}</div></div>
<section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><article className="rounded-2xl border bg-white p-4 dark:bg-neutral-900"><p className="text-xs text-slate-500">Ingresos netos acreditados</p><p className="mt-2 text-2xl font-bold">{money(kpis?.ingresos_neto_total)}</p><p className="mt-1 text-xs text-slate-400">Pagos reales del período</p></article><article className="rounded-2xl border bg-white p-4 dark:bg-neutral-900"><p className="text-xs text-slate-500">Total cobrado</p><p className="mt-2 text-2xl font-bold">{money(kpis?.ingresos_con_iva)}</p><p className="mt-1 text-xs text-slate-400">Con IVA cuando corresponda</p></article><article className="rounded-2xl border bg-white p-4 dark:bg-neutral-900"><p className="text-xs text-slate-500">MRR vigente estimado</p><p className="mt-2 text-2xl font-bold">{money(kpis?.mrr_neto)}</p><p className="mt-1 text-xs text-slate-400">Según ciclos pagos actuales</p></article><article className="rounded-2xl border bg-white p-4 dark:bg-neutral-900"><p className="text-xs text-slate-500">Empresas que pagaron</p><p className="mt-2 text-2xl font-bold">{kpis?.empresas_activas??0}</p><p className="mt-1 text-xs text-slate-400">Dentro del período elegido</p></article></section>
<section className="overflow-hidden rounded-2xl border bg-white dark:bg-neutral-900"><div className="flex items-center justify-between border-b p-4"><div><h2 className="font-semibold">Empresas</h2><p className="text-xs text-slate-500">Resumen mínimo; abrí cada empresa para ver movimientos y ciclos.</p></div><span className="text-xs text-slate-500">{empresas?.total??0}</span></div><div className="divide-y">{(empresas?.items??[]).length===0?<p className="p-4 text-sm text-slate-500">Sin resultados.</p>:(empresas?.items??[]).map(e=><article key={e.empresa_id} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 p-4 hover:bg-slate-50 dark:hover:bg-neutral-800"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="truncate font-semibold">{e.empresa_nombre}</h3><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${e.estado_acceso==="activa"?"bg-emerald-50 text-emerald-700":e.estado_acceso==="suspendida"?"bg-red-50 text-red-700":"bg-amber-50 text-amber-700"}`}>{e.estado_acceso==="activa"?"Activa":e.estado_acceso==="suspendida"?"Suspendida":"Sin ciclo"}</span></div><p className="mt-1 truncate text-xs text-slate-500">{e.plan_nombre||"Sin plan vigente"} · Ciclo hasta {date(e.fecha_fin)}</p><p className="mt-1 text-xs font-medium text-slate-700 dark:text-slate-300">Cobrado: {money(e.ingresos_neto_periodo)} · {e.movimientos_count} pago(s)</p></div><a href={`/dashboard/admin/cashflow/${encodeURIComponent(e.empresa_id)}?desde=${desde}&hasta=${hasta}`} className="shrink-0 rounded-xl border px-3 py-2 text-sm font-semibold hover:bg-slate-50">Ver detalle</a></article>)}</div></section>
<footer className="flex flex-col items-center justify-between gap-3 sm:flex-row"><div className="flex items-center gap-2"><span className="text-sm text-slate-500">Página {page} de {pages}</span><select value={pageSize} onChange={e=>{setPage(1);setPageSize(Number(e.target.value))}} className="rounded-lg border bg-transparent px-2 py-1 text-sm"><option value={10}>10</option><option value={20}>20</option><option value={50}>50</option></select></div><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-40">Anterior</button><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)} className="rounded-xl border px-4 py-2 text-sm disabled:opacity-40">Siguiente</button></div></footer></section>}
